# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pares.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bpares.proto\x12\x05pares\"*\n\x04reqR\x12\x12\n\nid_servico\x18\x01 \x01(\t\x12\x0e\n\x06\x63haves\x18\x02 \x03(\x05\"\x1a\n\x04mapa\x12\x12\n\nid_servico\x18\x01 \x01(\t\"$\n\x04reqI\x12\r\n\x05\x63have\x18\x01 \x01(\x05\x12\r\n\x05valor\x18\x02 \x01(\t\"\x1b\n\x08insercao\x12\x0f\n\x07retorno\x18\x01 \x01(\x05\"\x15\n\x04reqC\x12\r\n\x05\x63have\x18\x01 \x01(\x05\"\x19\n\x08\x63onsulta\x12\r\n\x05valor\x18\x01 \x01(\t\"\x12\n\x04reqA\x12\n\n\x02id\x18\x01 \x01(\t\"\x14\n\x04\x63ont\x12\x0c\n\x04\x63ont\x18\x01 \x01(\x05\"\x06\n\x04reqT\"\x1a\n\x07termino\x12\x0f\n\x07retorno\x18\x01 \x01(\x05\x32\xb3\x01\n\rServidorPares\x12\'\n\x07Inserir\x12\x0b.pares.reqI\x1a\x0f.pares.insercao\x12(\n\x08\x43onsulta\x12\x0b.pares.reqC\x1a\x0f.pares.consulta\x12$\n\x08\x41tivacao\x12\x0b.pares.reqA\x1a\x0b.pares.cont\x12)\n\nTerminacao\x12\x0b.pares.reqT\x1a\x0e.pares.termino2\x84\x01\n\x0fServidorCentral\x12$\n\x08Registro\x12\x0b.pares.reqR\x1a\x0b.pares.cont\x12 \n\x04Mapa\x12\x0b.pares.reqC\x1a\x0b.pares.mapa\x12)\n\nTerminacao\x12\x0b.pares.reqT\x1a\x0e.pares.terminob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pares_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQR']._serialized_start=22
  _globals['_REQR']._serialized_end=64
  _globals['_MAPA']._serialized_start=66
  _globals['_MAPA']._serialized_end=92
  _globals['_REQI']._serialized_start=94
  _globals['_REQI']._serialized_end=130
  _globals['_INSERCAO']._serialized_start=132
  _globals['_INSERCAO']._serialized_end=159
  _globals['_REQC']._serialized_start=161
  _globals['_REQC']._serialized_end=182
  _globals['_CONSULTA']._serialized_start=184
  _globals['_CONSULTA']._serialized_end=209
  _globals['_REQA']._serialized_start=211
  _globals['_REQA']._serialized_end=229
  _globals['_CONT']._serialized_start=231
  _globals['_CONT']._serialized_end=251
  _globals['_REQT']._serialized_start=253
  _globals['_REQT']._serialized_end=259
  _globals['_TERMINO']._serialized_start=261
  _globals['_TERMINO']._serialized_end=287
  _globals['_SERVIDORPARES']._serialized_start=290
  _globals['_SERVIDORPARES']._serialized_end=469
  _globals['_SERVIDORCENTRAL']._serialized_start=472
  _globals['_SERVIDORCENTRAL']._serialized_end=604
# @@protoc_insertion_point(module_scope)
